<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
            crossorigin="anonymous"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <title>Reports</title>
    <style>
        #reports {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        #reports td, #reports th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #reports tr:nth-child(even){background-color: #f2f2f2;}

        #reports tr:hover {background-color: #ddd;}

        #reports th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #03254c;
            color: white;
        }
    </style>
</head>
<body>
<div class="container-fluid">
    <div class="row text-center">
        <img src="{{ $image }}" style="height: 100px; width: 100px">
        <p class="fw-semibold mt-2">Pangasinan State University</p>
        <p class="fw-normal mt-1">Project Management System</p>
        <p class="fw-normal mt-1">Report</p>
    </div>
    <div class="row">
        @if ($reports != null)
            @foreach($reports as $report)
                <h1>{{ $report->project_title }} </h1>
                @break
            @endforeach
        @endif
    </div>
    <hr>
    <table id="reports">
        <thead>
            <tr>
                <th>Project Name</th>
                <th>Employee Name</th>
                <th>Action</th>
                <th>Role</th>
                <th>Moved At</th>
            </tr>
        </thead>
        <tbody>
            @if($reports != null)
                @foreach($reports as $report)
                    <tr>
                        <td>{{ $report->project_title }}</td>
                        <td>{{ $report->name }}</td>
                        <td>{{ $report->username }} {{ $report->message }}</td>
                        <td>{{ Str::upper($report->role) }}</td>
                        <td>{{ $report->report_date }}</td>
                    </tr>
                @endforeach
            @endif
        </tbody>
    </table>
    <hr>
    <div class="row">
        <div class="col-md-6"><p>Generated By: <b>{{ Str::upper(Auth::user()->name) }}</b></p></div>
        <div class="col-md-6"><p>Date Generated: <b>{{ \Carbon\Carbon::now() }}</b></p></div>
    </div>
</div>
</body>
</html>
